package httpapi

const (
	RouteArtists       = "/artists"
	RouteArtist        = "/artists/{id}"
	RouteArtistRelease = "/artists/{id}/releases"
	RouteLabels        = "/labels"
	RouteLabel         = "/labels/{id}"
	RouteLabelRelease  = "/labels/{id}/releases"
	RouteMasters       = "/masters"
	RouteMaster        = "/masters/{id}"
	RouteMasterRelease = "/masters/{id}/releases"
	RouteReleases      = "/releases"
	RouteRelease       = "/releases/{id}"
	RouteOpenAPI       = "/v3/api-docs"
	RouteOpenAPIJSON   = "/openapi.json"
	RouteVersion       = "/version"

	MethodGet = "GET"

	ParameterID       = "id"
	ParameterAfterID  = "after_id"
	ParameterSize     = "size"
	ParameterName     = "name"
	ParameterRealName = "real_name"
	ParameterTitle    = "title"
	ParameterCountry  = "country"
	ParameterYear     = "year"
	ParameterMonth    = "month"
	ParameterMaster   = "master"

	HeaderCacheControl           = "Cache-Control"
	HeaderContentLength          = "Content-Length"
	HeaderContentType            = "Content-Type"
	HeaderFrameOptions           = "X-Frame-Options"
	HeaderReferrerPolicy         = "Referrer-Policy"
	HeaderTypeOptions            = "X-Content-Type-Options"
	ContentTypeJSON              = "application/json"
	ContentTypeProblemJSON       = "application/problem+json"
	HeaderValueDeny              = "DENY"
	HeaderValueNoReferrer        = "no-referrer"
	HeaderValueNoSniff           = "nosniff"
	ProblemTypeAboutBlank        = "about:blank"
	ProblemTitleBadRequest       = "Bad Request"
	ProblemTitleNotFound         = "Not Found"
	ProblemTitleInternal         = "Internal Server Error"
	ProblemTitleTimeout          = "Gateway Timeout"
	ProblemDetailNotFound        = "resource not found in imported dump snapshot"
	ProblemDetailInternal        = "request processing failed"
	ProblemDetailTimeout         = "database query timed out"
	MaximumResourceID      int64 = 1<<31 - 1
)
