apiVersion: v1
kind: Secret
metadata:
  name: go-open-discogs-api
  namespace: open-discogs
type: Opaque
stringData:
  API_DATABASE_URL: "postgres://readonly:replace-me@postgres.example.com:5432/discogs?sslmode=require"
